"""Add column city.

Revision ID: d82db4d9e8e8
Revises: 7395ac0eb992
Create Date: 2023-02-23 20:10:45.000749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82db4d9e8e8'
down_revision = '7395ac0eb992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
